### ISSUE TITLE
Doesn't work with synced folders owned by other user

### ISSUE THREAD

**Issue by yolk** [mhallin/vagrant-notify-forwarder#10]
Because the notify-forwarder started on the client/guest is run as the user vagrant uses for SSH, it is not possible to trigger events on a synced folder owned by another user.

I see two possible solutions:
- Add a new config option to run the forwarder as another user. Could be problematic because the user may only exit after provisioning.
- Add a new config option to run the forwarder as root. Not sure about the security implications but the would solve the issue even if there are multiple synced folders owned by different users.

It should at least detect in start_client_forwarder.rb if the synced folders are owned by another user and log a warning. I had to hunt down the problem several hours...

What do you think?

**Comment by mhallin** [comment]
Interesting case. I've modified release 0.5.0 to run as root (through `sudo`) by default, with an option to disable this. I'm not overly concerned about the security issue - this is a development tool and the receiver can only perform the equivalent of `touch`.

Try updating to 0.5.0 and see if the issue has been resolved for you.

**Comment by yolk** [comment]
Thanks for the change! Works perfect now, after updating to 0.5.0.
