### ISSUE TITLE
High Sierra (10.13.3) Kernel Panic while changing many files

### ISSUE THREAD

**Issue by asottile** [mhallin/vagrant-notify-forwarder#19]
(mostly opening here for more visibility)

See: https://github.com/mhallin/notify-forwarder/issues/4

**Comment by wesrice** [comment]
Thanks @asottile. I've lost almost two days trying to figure this out.

**Comment by asottile** [comment]
Just to circle back here, apple closed the issue and it appears fixed in Mojave!
